# Generated by Django 4.1.3 on 2022-11-07 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MARCA', models.CharField(max_length=40)),
                ('MODELO', models.CharField(max_length=40)),
                ('TIPO_EQUIPO', models.CharField(max_length=40)),
                ('NO_SERIE', models.CharField(max_length=40)),
                ('TIPO_DD', models.CharField(blank=True, max_length=40)),
                ('ESPACIO_DD', models.BigIntegerField()),
                ('RAM', models.CharField(blank=True, max_length=5)),
                ('T_RAM', models.CharField(blank=True, max_length=5)),
                ('SYS_OP', models.CharField(blank=True, max_length=30)),
                ('MAC', models.CharField(blank=True, max_length=20)),
                ('IP', models.CharField(blank=True, max_length=17)),
                ('TEAMVIEWER', models.CharField(blank=True, max_length=11)),
                ('ANYDESK', models.CharField(blank=True, max_length=12)),
                ('CREATEDAT', models.DateTimeField(auto_now_add=True)),
                ('DESCRIPTION', models.CharField(blank=True, max_length=200)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
