# Generated by Django 4.1.3 on 2022-11-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='DESCRIPTION',
            field=models.TextField(blank=True),
        ),
    ]
