# Generated by Django 4.1.3 on 2022-11-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_equipo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='IP',
            field=models.GenericIPAddressField(),
        ),
    ]
