# Generated by Django 4.1.3 on 2022-11-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_equipo_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='SYS_OP',
            field=models.CharField(choices=[('WINDOWS 8', 'Windows 8'), ('WINDOWS 10 ENTERPRISE', 'Windows 10: Enterprise'), ('WINDOWS 10 PRO', 'Windows 10 Pro'), ('WINDOWS 11 PRO', 'Windows 11 Pro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='TIPO_EQUIPO',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('ESCRITORIO', 'Escritorio'), ('MONITOR', 'Monitor'), ('DVR', 'DVR'), ('NVR', 'NVR')], max_length=40),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='T_RAM',
            field=models.CharField(choices=[('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=5),
        ),
    ]
