# Generated by Django 4.1.3 on 2022-11-08 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_unidades_marca_alter_equipo_marca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MARCA', models.CharField(max_length=40)),
                ('RAZON_SOCIAL', models.CharField(choices=[('PLERSA', 'Plersa S.A. De C.V.'), ('RICODELI', 'Rico Deli'), ('RAW REPUBLIC', 'Raw Republic'), ('SACOM', 'Grupo Sacom')], max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='ANYDESK',
            new_name='ANYDESK_ID',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='DESCRIPTION',
            new_name='DESCRIPCION',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='ESPACIO_DD',
            new_name='ESPACIO_EN_DISCO',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='NO_SERIE',
            new_name='NUMERO_DE_SERIE',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='SYS_OP',
            new_name='SISTEMA_OPERATIVO',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='TEAMVIEWER',
            new_name='TEAMVIEWER_ID',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='TIPO_DD',
            new_name='TIPO_DE_DISCO',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='TIPO_EQUIPO',
            new_name='TIPO_DE_EQUIPO',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='T_RAM',
            new_name='TIPO_DE_RAM',
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UNIDAD', models.CharField(max_length=40)),
                ('TERMINAL', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2')], max_length=2)),
                ('UBICACION', models.CharField(choices=[('ANTENAS', 'Plaza las Antenas'), ('DELTA', 'Parque Delta'), ('TEZONTLE', 'Tezontle'), ('LINDAVISTA', 'Parque Lindavista'), ('AICM', 'AICM'), ('AIFA', 'AIFA')], max_length=30)),
                ('MARCA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.marcas')),
            ],
        ),
        migrations.AlterField(
            model_name='equipo',
            name='MARCA',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.unidades'),
        ),
    ]
