# Generated by Django 4.1.3 on 2022-11-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_marcas_rename_anydesk_equipo_anydesk_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marcas',
            old_name='MARCA',
            new_name='NOMBRE',
        ),
    ]
