# Generated by Django 4.1.3 on 2022-11-08 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_marca_marcas_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidades',
            name='MARCA',
        ),
        migrations.DeleteModel(
            name='Marcas',
        ),
    ]
