# Generated by Django 4.1.3 on 2022-11-08 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_unidades_marca_delete_marcas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidades',
            old_name='UNIDAD',
            new_name='NOMBRE',
        ),
        migrations.AddField(
            model_name='equipo',
            name='UNIDAD',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.unidades'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='MARCA',
            field=models.CharField(max_length=40),
        ),
    ]
