# Generated by Django 4.1.3 on 2022-11-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rename_unidad_unidades_nombre_equipo_unidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='RAM',
            field=models.CharField(blank=True, choices=[('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '12 GB'), ('24 GB', '24 GB'), ('32 GB', '32 GB')], max_length=5),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='TERMINAL',
            field=models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4')], max_length=2),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='UBICACION',
            field=models.CharField(choices=[('AICM', 'AICM'), ('AIFA', 'AIFA'), ('ANTENAS', 'Plaza las Antenas'), ('DELTA', 'Parque Delta'), ('TEZONTLE', 'Tezontle'), ('LINDAVISTA', 'Parque Lindavista'), ('PUERTO_VALLARTA', 'Puerto Vallarta'), ('PLAYA_DEL_CARMEN', 'Playa del Carmen'), ('GUADALAJARA', 'Guadalajara'), ('MONTERREY', 'Monterrey'), ('CANCUN', 'Cancún')], max_length=30),
        ),
    ]
